on:
  workflow_call:
    secrets:
      dockerhub_username:
        required: true
      dockerhub_password:
        required: true
      dockerhub_registry:
        required: false
      dockerhub_repository:
        required: true
      dockerhub_tag:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push (PR)
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.dockerhub_username }}/${{ secrets.dockerhub_repository }}:${{ secrets.dockerhub_tag }}
          cache-from: type=registry,ref=${{ secrets.dockerhub_username }}/${{ secrets.dockerhub_repository }}:buildcache-${{ secrets.dockerhub_tag }}
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.dockerhub_repository }}:buildcache-${{ secrets.dockerhub_tag }},mode=max